name: Github Action

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Setup Android Tools
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: ndk;24.0.8215888
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
