name: Test Build CI

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 0x01 - system update & upgrade
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

      - name: 0x02 - firmware update install
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -xf immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst --zstd
          cd immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64
          echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> "feeds.conf.default"
          echo "src-git tcp_brutal https://github.com/haruue-net/openwrt-tcp-brutal.git;master" >> "feeds.conf.default"
          ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: 0x04 - firmware start build !!
        run: |
          cd immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64
          make defconfig
          make package/luci-app-nikki/compile
          make package/feeds/tcp_brutal/tcp-brutal/compile

      - uses: actions/upload-artifact@v4
        with:
          name: openwrt-nikki-ipk
          path: immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64/bin/packages/x86_64/nikki

      - uses: actions/upload-artifact@v4
        with:
          name: openwrt-brutal-ipk
          path: immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64/bin/targets/x86/64/packages
