name: Test Build CI

on:
  watch:
    types: started

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
